"""initial

Revision ID: 0001
Revises:
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('person_name', sa.Text(), nullable=False),
    sa.Column('company_name_raw', sa.Text(), nullable=False),
    sa.Column('company_name_canonical', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('designation', sa.Text(), nullable=True),
    sa.Column('participation_type', sa.Text(), nullable=True),
    sa.Column('tech_category', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('preferred_contact_time', sa.Text(), nullable=True),
    sa.Column('consent_status', sa.String(length=16), nullable=False),
    sa.Column('intent_hint', sa.String(length=24), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_dossiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquiry_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('person_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('person_company_match', sa.Boolean(), nullable=True),
    sa.Column('relationship', sa.String(length=16), nullable=False),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('peer_companies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ask_prospect', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('research_cost', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquiry_id', sa.UUID(), nullable=False),
    sa.Column('dossier_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('persona', sa.String(length=24), nullable=True),
    sa.Column('target_cta', sa.String(length=32), nullable=True),
    sa.Column('cta_status', sa.String(length=16), nullable=False),
    sa.Column('cta_type', sa.String(length=32), nullable=True),
    sa.Column('cta_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome_status', sa.String(length=16), nullable=True),
    sa.Column('handoff_generated', sa.Boolean(), nullable=False),
    sa.Column('learned_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('persona_remapped', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['research_dossiers.id'], ),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('guardrail_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_intent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('handoff_packets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommended_next_step', sa.Text(), nullable=True),
    sa.Column('suggested_followup_message', sa.Text(), nullable=True),
    sa.Column('prospect_confidence', sa.String(length=8), nullable=True),
    sa.Column('key_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivered_to', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('handoff_packets')
    op.drop_table('chat_messages')
    op.drop_table('chat_sessions')
    op.drop_table('research_dossiers')
    op.drop_table('inquiries')
    # ### end Alembic commands ###
