"""Human-triggered CLI entrypoint for the TEG-claim verification harness.

See docs/superpowers/specs/2026-09-10-verification-harness-and-graph-design.md
§3.1.6. No scheduler here — a human runs this, or (a separate, later change)
a cron job calls it with --all.

    python scripts/run_verification.py <claim-id>
    python scripts/run_verification.py --all
"""
from __future__ import annotations

import asyncio
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.verify.claims import CLAIMS
from app.verify.claude_verifier import verify_all, verify_claim
from app.verify.schemas import VerificationResult
from config.settings import get_settings

_LOG_DIR = (
    Path(get_settings().kb_path).resolve().parent / "_verification_log"
)


def _write_log(results: list[VerificationResult]) -> Path:
    _LOG_DIR.mkdir(parents=True, exist_ok=True)
    today = datetime.now(UTC).date().isoformat()
    path = _LOG_DIR / f"{today}.md"
    lines = [
        f"# Verification pass — {today}",
        "",
        "| Claim | KB says | Web says | Status | Sources | Checked |",
        "|---|---|---|---|---|---|",
    ]
    for r in results:
        sources = ", ".join(r.sources) or "-"
        lines.append(
            f"| {r.claim} | {r.kb_says} | {r.web_says or '-'} | {r.status} | "
            f"{sources} | {r.checked_at.isoformat()} |"
        )
    lines += [
        "",
        "*Generated by `scripts/run_verification.py`. This is a staging file, "
        "not a sourced KB claim — a human reviews it and merges anything "
        "confirmed-changed into the relevant topic file by hand, the same "
        "review discipline `scripts/build_kb_facts.py --check` already "
        "enforces for the guardrail snapshot.*",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def _print_summary(results: list[VerificationResult]) -> None:
    for r in results:
        print(f"{r.claim}: {r.status}" + (f"  — {r.web_says}" if r.web_says else ""))


async def _run(argv: list[str]) -> int:
    if not argv:
        print(__doc__, file=sys.stderr)
        return 2
    if argv[0] == "--all":
        results = await verify_all()
    else:
        claim = CLAIMS.get(argv[0])
        if claim is None:
            print(f"unknown claim id {argv[0]!r} — known: {sorted(CLAIMS)}", file=sys.stderr)
            return 2
        result, _ = await verify_claim(claim)
        results = [result]

    path = _write_log(results)
    _print_summary(results)
    print(f"wrote {path}")
    return 1 if any(r.status == "conflicting" for r in results) else 0


def main() -> int:
    return asyncio.run(_run(sys.argv[1:]))


if __name__ == "__main__":
    raise SystemExit(main())
